authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit


app_name = 'authapp'

urlpatterns = [
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

basketapp/urls.py
from django.urls import path

from .views import basket


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='index'),
]

mainapp/urls.py
from django.urls import path

from mainapp.views import gallery, upload_to_gallery


app_name = 'mainapp'

urlpatterns = [
    path('', gallery, name='index'),
    path('upload/', upload_to_gallery, name='upload_to_gallery')
]

shopapp/urls.py
from django.urls import path, include

from shopapp.views import product, by_category


app_name = 'shopapp'

urlpatterns = [
    path('', product, name='index'),
    path('<int:category_id>/', by_category, name='by_category'),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

training_page/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('gallery/', include('mainapp.urls', namespace='gallery')),
    path('shop/', include('shopapp.urls', namespace='shop')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AuthUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)
    age = models.PositiveIntegerField(verbose_name='Возраст', blank=True)

basketapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models


class Picture(models.Model):
    image = models.ImageField(upload_to='gallery_image')
    comment = models.TextField(blank=True)

shopapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product_image', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return f'{self.name} | {self.category.name}'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from django import forms

from .models import AuthUser


class AuthUserLoginForm(AuthenticationForm):
    class Meta:
        model = AuthUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(AuthUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = AuthUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("You are too young")

        return data


class UserEditForm(UserChangeForm):
    class Meta:
        model = AuthUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("You are too young")

        return data

mainapp/forms.py
from django import  forms

from .models import Picture


class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ('image', 'comment')

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from authapp.forms import AuthUserLoginForm, UserRegisterForm, UserEditForm


def login(request):
    title = 'вход'

    login_form = AuthUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'register'

    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = UserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'EditUser'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = UserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

basketapp/views.py
from django.shortcuts import render



def basket(request):
    return render(request, 'basketapp/basket.html')

mainapp/views.py
from django.shortcuts import render
from .models import Picture

from .forms import PictureForm


def index(request):
    return render(request, 'mainapp/index.html')

def gallery(request):
    pictures = Picture.objects.all()
    content = {'pictures': pictures}
    return render(request, 'mainapp/gallery.html', content)


def upload_to_gallery(request):

    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            return  render(request, 'mainapp/upload_to_gallery.html', {'form': form, 'img_obj': img_obj})
    else:
        form = PictureForm()
    return render(request, 'mainapp/upload_to_gallery.html', {'form': form})

shopapp/views.py
from django.shortcuts import render

from shopapp.models import Product, ProductCategory

def product(request):
    products = Product.objects.all()
    categories = ProductCategory.objects.all()
    content = {'products': products, 'categories': categories}
    return render(request, 'shopapp/product.html', content)


def by_category(request, category_id):
    products = Product.objects.filter(category = category_id)
    category = ProductCategory.objects.all()
    current_category = ProductCategory.objects.get(pk=category_id)
    content = {
        'products': products, 'category': category, 'current_category': current_category
    }
    return render(request, 'shopapp/by_category.html', content)

authapp/templates/authapp/base.html
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>            
            
            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>   

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'index' %}" class="">
            main
        </a>
    </button>
    <div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}

basketapp/templates/basketapp/basket.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>qwe</p>
</body>
</html>

mainapp/templates/mainapp/gallery.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gallery</title>

    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>
<body>
<a href="{% url 'index' %}">main</a>

    {% for picture in pictures %}
        <img width="400" src="/media/{{ picture.image }}" alt="">
        <p>{{ picture.comment }}</p>
    {% endfor %}

</body>
</html>

mainapp/templates/mainapp/index.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>

    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>
<body>

    <div class="nav">
        <ul>
            <li><a href="{% url 'auth:login' %}">Login</a></li>
            <li><a href="{% url 'auth:register' %}">Sing up</a></li>
            <li><a href="https://github.com/olegkraynenkov/training_page">Github</a></li>
        </ul>

    </div>

    <div class="menu-main">
        <a href="{% url 'gallery:index' %}">GALLERY</a>
        <a href="{% url 'shop:index' %}">SHOP</a>
    </div>
</body>
</html>

mainapp/templates/mainapp/upload_to_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.comment}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}

</body>
</html>

shopapp/templates/shopapp/by_category.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for product in products %}

        <h3>{{ product.name }}</h3>

    {% endfor %}
</body>
</html>

shopapp/templates/shopapp/product.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Product</title>
        <link href="{% static 'css/shop.css' %}" rel="stylesheet">
    </head>
<body>
<div class="content">
    <ul class="nav">
        <li><a href="{% url 'index' %}" class="current">Main</a></li>
        <li><a href="{% url 'gallery:index' %}">Gallery</a></li>
    </ul>

    {% for category in categories %}

    <a href="{% url 'shop:by_category' category.pk %}">{{ category.name }}</a>

    {% endfor %}

    <div class="product-item">
    {% for product in products %}
    <img src="/media/{{ product.image }}" alt="">
  <div class="product-list">
    <h3>{{ product.name }}</h3>
    <span class="price">{{ product.price }}</span>
    <a href="" class="button">В корзину</a>
  </div>
        {% endfor %}
    </div>
</div>

<footer>
    <p> poopa </p>
</footer>
</body>
</html>